### ISSUE TITLE
[Bug]: Velocity

### ISSUE THREAD

**Issue by GabrieleYT9768** [pelican-eggs/minecraft#12]
### Panel Version

1.0.0-beta3

### Wings Version

1.0.0-beta3

### Service

proxy/velocity

### Modified

No, I did not modify the egg

### Expected Behavior

When I run the server, the config in the velocity.toml file should change the bind_address value to "0.0.0.0:{{SERVER_PORT}}" as its specified in its Configuration Files field:
```json
{
    "velocity.toml": {
        "parser": "file",
        "find": {
            "bind = ": "bind = \"0.0.0.0:{{server.build.default.port}}\""
        }
    }
}
```

### Actual Behavior

Instead, every time I run my server the bind_address value changes to:
```toml
bind = "0.0.0.0:"
```

### Steps To Reproduce

- Create a Velocity Server on your panel
- Start the server
Now the server will run on port 25565 or 25577, because its the default port that velocity applies to your server. Even if you try to manually edit the velocity.toml file to replace the port, every time you restart the server the bind_address gets replaced again with the wrong port.

### Install logs

https://pteropaste.com/8kw6

**Comment by GabrieleYT9768** [comment]
Every time I said `bind_address` value I meant the `bind` value, I just confused.

**Comment by QuintenQVD0** [comment]
Please read the discord announcement for that. Its broken, we know.

**Comment by GabrieleYT9768** [comment]
oh sorry
