### ISSUE TITLE
Egg request for minecraft bedrock levilamina

### ISSUE THREAD

**Issue by LuChen411** [pelican-eggs/minecraft#13]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/LiteLDev/LeviLamina

### Links for the download

https://github.com/LiteLDev/LeviLamina

### Links for the install docs

https://github.com/LiteLDev/LeviLamina

**Comment by gOOvER** [comment]
This repo is read-only and not longer used

**Comment by gOOvER** [comment]
its windows only

**Comment by LuChen411** [comment]
> its windows only. I dont see any linux builds and Bedrock is a Linuxserver. So its not possible

https://github.com/LiteLDev/docker-levilamina-server
how about this？

**Comment by gOOvER** [comment]
The egg do not run with wine. Again, Bedrock is a native linux server. Ask the dev, to provide linux binaries

**Comment by LuChen411** [comment]
> The egg do not run with wine. Again, Bedrock is a native linux server. Ask the dev, to provide linux binaries

I have seen a wine version in that link

**Comment by QuintenQVD0** [comment]
Their dev branch does not even build at all right now

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/pelican-eggs/minecraft/assets/67589015/456e59c0-60ad-48d3-b66c-e4b7ca6147f8)
