### ISSUE TITLE
[Bug]: Purpur-Geyser-Floodgate

### ISSUE THREAD

**Issue by Erani0** [pelican-eggs/minecraft#16]
### Panel Version

1.11.7

### Wings Version

1.11.8

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

Egg not download anything

### Actual Behavior

Using the latest purpur version
Using the latest purpur build for version 1.21
Version being downloaded
MC Version: 1.21
Build: 2238
JAR Name of Build: purpur-1.21-2238.jar
Downloading the requested purpur buid with curl -o server.jar https://api.purpurmc.org/v2/purpur/1.21/2238/download
curl: option -sSL-o: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Downloading last successful build with curl -o plugins/geyser-spigot https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
curl: (6) Could not resolve host: plugins
Downloading last successful build with curl -o plugins/floodgate-spigot.jar https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
curl: (6) Could not resolve host: plugins
Installation Finished

### Steps To Reproduce

Step 1 Version latest
Install not working

### Install logs

https://pteropaste.com/xqd8

**Comment by Draakoor** [comment]
there is just a space missing between -ssl and -o

**Comment by TastyToast000** [comment]
> b

After I fixed that I got an error something like could not resolve host: plugins. The egg also isn't set to Java 21 which is required. I was hoping the egg file could be fixed by flagging down the right person.

**Comment by Draakoor** [comment]
Opened a Pull Request to fix all of thoose

**Comment by TastyToast000** [comment]
> Opened a Pull Request to fix all of thoose

I can't figure out how to get it to update geyser/floodgate on startup

**Comment by QuintenQVD0** [comment]
> > Opened a Pull Request to fix all of thoose
> 
> I can't figure out how to get it to update geyser/floodgate on startup

It wont ever do that withoud a custom non supprted image.

**Comment by TastyToast000** [comment]
So this only downloads geyser and floodgate for initial install?

**Comment by QuintenQVD0** [comment]
> So this only downloads geyser and floodgate for initial install?

Yes like all dggs? If you want to update you have to hit reinstall. Thats litteely with all eggs exept the steamcmd ones.

**Comment by Draakoor** [comment]
You can try this: https://left4craft.github.io/spigot-updater/
But I never used it before

**Comment by QuintenQVD0** [comment]
> You can try this: https://left4craft.github.io/spigot-updater/ But I never used it before

No need for it. It will not be implemented. If you want to update a mc server you should always tell it to do it. Some things may brake.
