### ISSUE TITLE
[Bug]: Minecraft Bedrock not updating to latest version available

### ISSUE THREAD

**Issue by JustinHoeky** [pelican-eggs/minecraft#9]
### Panel Version

1.11.5

### Wings Version

1.11

### Service

minecraft bedrock

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Expected behaviour is to update to latest version when using "latest"

### Actual Behavior

Stuck on version 1.20.41.02 while clients are running on 1.20.81

### Steps To Reproduce

Set version to latest
Run server, still runs 1.20.41 and tells it's up-to-date

Setting version to 1.20.81 doensnt help either

### Install logs

https://pteropaste.com

**Comment by QuintenQVD0** [comment]
No install logs, and withoud a reinstall it will not update

and client and server version do not always have the version nummer.

**Comment by JustinHoeky** [comment]
> No install logs, and withoud a reinstall it will not update
> 
> and client and server version do not always have the version nummer.

I think my copy-paste of the install logs went wrong.
Reinstalling did the trick, now running 1.20.81

Thank you!!
